gems:
  - jekyll-seo-tag
  - octopress-minify-html

permalink: pretty
home_url: "https://jeaye.com"
#home_url: "http://0.0.0.0:4000"
blog_url: "https://blog.jeaye.com"
#blog_url: "http://0.0.0.0:4001"
url: "https://jeaye.com"
license_url: "https://github.com/jeaye/jeaye.com/blob/gh-pages/LICENSE"
tagline: "I'm a systems-level functional programmer with a passion for safety and security."

# TODO: Setup a nice font
sass:
  sass_dir: css-partial
  style: compressed

# This is a hack to allow me to include anything in the repo. I use it to inline
# css in the header.
includes_dir: .

markdown: kramdown
kramdown:
  input: GFM
  syntax_highligher: rouge

exclude: [.bundle, vendor, Gemfile, Gemfile.lock, node_modules, img-partial, css-partial, generate-sprite-sheet, run, publish, blog, package.json, package-lock.json]
