plugins:
  - jekyll-seo-tag
  - jekyll-assets
  - octopress-minify-html

permalink: pretty
home_url: "/"
blog_url: "https://blog.jeaye.com/"
#blog_url: "http://0.0.0.0:4001/"
url: "https://jeaye.com/"
license_url: "https://github.com/jeaye/jeaye.com/blob/gh-pages/LICENSE"
tagline: "I'm a leader, a problem solver, and a hacker with a passion for privacy and security."

# TODO: Setup a nice font

assets:
  # Generate files with names based on their content hash.
  digest: true
  features:
    automatic_img_size: false
    automatic_img_alt : false

markdown: kramdown
kramdown:
  input: GFM
  syntax_highligher: rouge

exclude: [.bundle, .asset-cache, vendor, Gemfile, Gemfile.lock, node_modules, img-partial, css-partial, generate-sprite-sheet, run, publish, blog, package.json, package-lock.json]
