#!/usr/bin/env bash

# TODO: install sprity-cli when needed

node ./node_modules/sprity-cli/index.js \
    create ./img img-partial/*.png \
    -s sprite-sheet.css \
    -c /img \
    -n sprite-sheet
mv -f ./img/sprite-sheet.png ./img/sprite-sheet.png
mv -f ./img/sprite-sheet.css ./css-partial/sprite-sheet.scss
