#!/usr/bin/env bash

set -eu

[ ! -d ./node_modules ] && npm install

node ./node_modules/sprity-cli/index.js \
    create _assets/img _assets/img-partial/*.png \
    -e sprity-jimp \
    -s sprite-sheet.css \
    -c "" \
    -n sprite-sheet
mv -f _assets/img/sprite-sheet.css _assets/css/sprite.scss
sed -i 's/.*: url.*//' _assets/css/sprite.scss
