#!/usr/bin/env bash

set -eu

[ ! -d ./node_modules/sprity-cli ] && npm install sprity-cli
[ ! -d ./node_modules/sprity-lwip ] && npm install https://github.com/chadwatson/sprity-lwip.git

node ./node_modules/sprity-cli/index.js \
    create ./img img-partial/*.png \
    -s sprite-sheet.css \
    -c /img \
    -n sprite-sheet
mv -f ./img/sprite-sheet.png ./img/sprite-sheet.png
mv -f ./img/sprite-sheet.css ./css-partial/sprite-sheet.scss
