#!/usr/bin/env bash

set -eu

cleanup()
{
  [ -z ${tmp+x} ] || rm -rf "$tmp"
}
trap cleanup EXIT

rm -rf ./_site

./generate-sprite-sheet

export JEKYLL_ENV=production
bundle-2.3 exec jekyll build

# TODO: Check for optipng and fail if not present
for img in _site/img/*.png;
do
  optipng -q "$img"
done

tmp=$(mktemp -d)
cp -r _site/* "$tmp"/
cp -r .git "$tmp"/
pushd "$tmp"
  git checkout -B gh-pages
  git add .
  git commit -am "Publish updates"
  git push -f origin HEAD
popd
