#!/usr/bin/env bash

cleanup()
{
  [ -z ${tmp+x} ] || rm -vrf "$tmp"
}
trap cleanup EXIT

tmp=$(mktemp -d)
mv -v _site/* "$tmp"/
cp -rv .git "$tmp"/
pushd "$tmp"
  git checkout -B gh-pages
  git add .
  git reset HEAD -- vendor run publish Gemfile*
  git commit -am "Publish updates"
  git push -f origin HEAD
popd
