#!/usr/bin/env bash

cleanup()
{
  [ -z ${tmp+x} ] || rm -rf "$tmp"
}
trap cleanup EXIT

export JEKYLL_ENV=production
bundle exec jekyll build

tmp=$(mktemp -d)
cp _site/* "$tmp"/
cp -r .git "$tmp"/
pushd "$tmp"
  rm -rf ./vendor ./run ./publish ./Gemfile*
  git checkout -B gh-pages
  git add .
  git commit -am "Publish updates"
  git push -f origin HEAD
popd
